# frozen_string_literal: true

# generated by frozen:seo
module Sitemap
  module RobotsGeneratable
    extend ActiveSupport::Concern

    included do
      # include behavior to build robots.txt entries
    end

    # TODO: define helper methods for robots generation
  end
end
