# frozen_string_literal: true

# generated by frozen:seo
module Sitemap
  class Entry
    include ActiveModel::Model

    attr_accessor :url, :lastmod, :changefreq, :priority

    # TODO: add methods for timestamp determination
  end
end
