# frozen_string_literal: true

# generated by frozen:seo
# A placeholder sitemap model; adapt according to your needs.
# See docs/web-page-metadata.md and docs/sitemap-and-robots.md for guidance.

class Sitemap
  include ActiveModel::Model

  attr_accessor :base_url, :build_dir, :generate_robots

  validates :base_url, :build_dir, presence: true

  # TODO: implement generation logic
end
