# frozen_string_literal: true

# generated by frozen:db
# Minimal Avo configuration; adjust as needed.
Avo.configure do |config|
  config.root_path = "/avo"
  config.authorization_client = nil
  config.explicit_authorization = true
  config.click_row_to_view_record = true
end
