# frozen_string_literal: true

# generated by frozen:db
FriendlyId.defaults do |config|
  # enable the most common modules
  config.use :reserved
  config.use :slugged
  config.use :finders
  config.use :history

  # a UUID will be appended automatically when a unique slug cannot be generated
  # suitable reserved words to avoid can be declared here.
  config.reserved_words = %w[new edit index session login logout users admin]
end
